# https://taskfile.dev

version: '3'

vars:
  PROJECT: Beacon
  GO: go

tasks:
  default:
    deps: [beacon]

  beacon:
    silent: false
    sources:
      - ./cmd/beacon/**/*
      - ./Taskfile.yml
    generates:
      - ./beacon.exe
    cmds:
     - "{{.GO}} vet ./cmd/beacon/main.go"
     - "{{.GO}} build -o beacon.exe ./cmd/beacon/main.go"

  buildDbg:
    cmds:
     - echo "OS = {{OS}}"